# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'OzMOmvIBqyj8ksfCwUgY1RMN_gpZ5n19'
  redis: 'qXyQS3b5QKzoresp131kepkVpx3DBFds'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'tvBdSWlAXrR3vNK8Eef9K0Qv_9vhfwKb'

test:
  database: 'P6JFQXcCPKRdsrCFVilfZtT4lO3p7AvR'
  redis: 'yQdumQ3FDjl6GszUuD8I03dU9mgpTje2'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'r87a9lcvQKf_Aajsbzhv6NcBNaZQOq2Q'
  serviceSecret: 'Jk0hvEyVlo6KOtxeMioMgWmU2bs0iee3'

# Passwords used in production mode.
production:
  database: 'uOYe25pe0mzUT9qYWjVe19-bjA3giIFu'
  serviceSecret: 'Ea1fpgCjDsTWLrQB21HXplpqJt96VJ4l'
