name: flearn
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  bloc_test: ^10.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_animate: ^4.5.2

  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  flutter_riverpod: ^2.6.1
  get_it: ^7.7.0
  get_it_mixin: ^4.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  material_color_utilities: ^0.11.1
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  stream_transform: ^2.1.1
  mobx: ^2.5.0
  meta: ^1.15.0
  get: ^4.6.6
  font_awesome_flutter: ^10.8.0
  flutter_blue_plus: ^1.35.2
  permission_handler: ^11.3.1
  serverpod_flutter: 2.3.1
#  my_pod_client:
#    path: ../my_pod_client
  my_store_serverpod_backend_client:
    path: ../my_store_serverpod_backend/my_store_serverpod_backend_client
  twilio_flutter: ^0.9.0
#  http: ^1.2.2
  image_picker: ^1.1.2
  badges: ^3.1.2
  custom_rating_bar: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.2
  flutter_stripe: ^11.4.0
  #http: ^1.2.2
  cloudinary_public: ^0.23.1
  file_picker: ^8.3.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  uuid: ^4.5.1
  remove_bg: ^0.0.3
  path_provider: ^2.1.5
  image: ^4.5.2
  universal_io: ^2.2.2
  flutter_admin_scaffold: ^1.4.0
  window_manager: ^0.4.3
  photo_view: ^0.15.0
  flutter_keyboard_visibility: ^6.0.0
  fluttertoast: ^8.2.11
  flutter_cached_pdfview: ^0.4.3
  image_cropper: ^9.0.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.0.17
  figma_squircle: ^0.5.3
  url_launcher: ^6.3.1
  logger: ^2.5.0
  firebase_analytics: ^11.4.2
  firebase_crashlytics: ^4.3.2
  flutter_expandable_fab: ^2.3.0
#  boardview: ^0.2.2
  material_design_icons_flutter: ^7.0.7296
  crypto: ^3.0.6
  status_alert: ^1.0.1
#  empty_widget: ^0.0.5
  responsive_grid_list: ^1.4.0
  flutter_background_geolocation: ^4.16.6
  background_fetch: ^1.3.7
  geolocator: ^13.0.2
  internet_connection_checker: ^3.0.1
  rxdart: ^0.28.0
  talker_dio_logger: ^4.6.10
  package_info_plus: ^8.2.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.2
  flutter_timezone: ^4.1.0
  device_info_plus: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test:
  mocktail: ^1.0.4
  mockingjay: ^0.6.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Bold.ttf
        - asset: assets/fonts/Exo-Medium.ttf
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/

