name: flearn
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: '^8.1.4'
  bloc_concurrency: '^0.2.5'
  bloc_test: '^9.1.7'
  cached_network_image: '^3.4.1'
  cupertino_icons: '^1.0.8'
  dio: '^5.7.0'
  equatable: '^2.0.5'
  flutter_animate: '^4.5.0'
  flutter_bloc: '^8.1.6'
  flutter_localizations:
    sdk: flutter
  flutter_mobx: '^2.2.1+1'
  flutter_riverpod: '^2.6.1'
  get_it: '^7.7.0'
  get_it_mixin: '^4.2.2'
  google_fonts: '^6.2.1'
  intl: '^0.19.0'
  material_color_utilities: '^0.11.1'
  provider: '^6.1.2'
  shared_preferences: '^2.3.2'
  stream_transform: '^2.1.0'
  mobx: '^2.2.1+1'
  meta: '^1.15.0'
  get: '^4.6.6'
  font_awesome_flutter: ^10.8.0
  flutter_blue_plus: ^1.34.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '^5.0.0'
  test:
  mocktail: '^1.0.4'
  mockingjay: '^0.6.0'
  build_runner: '^2.4.13'
  mobx_codegen: '^2.6.1'

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Bold.ttf
        - asset: assets/fonts/Exo-Medium.ttf
  assets:
    - assets/fonts/
    - assets/images/
